### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by codemedic213515**

### CODE REVIEW

**Review by codemedic213515 — COMMENTED** [review]
You have to add more education info.

**Comment by struggle-Strug** [comment]
I think I can do that.

**Review by ledgerluminary55 — APPROVED** [review]

**Comment by billiedox** [comment]
Sure . I can do it.

**Review by CryptoSmile000 — APPROVED** [review]

**Comment by CryptoSmile000** [comment]
No problem😁

**Pull request merged**
